env:
  PROMETHEUS_YML_CONTENT: |
    global:
      scrape_interval: 15s

scrape_configs:
  - job_name: 'app_clima2'
    static_configs:
      - targets: ['app_clima:5000']  # Nombre del servicio o IP:puerto del contenedor/app
